name: Python Django CI/CD QA

on:
  push:
    branches:
      - qa

jobs:
  build_and_push_docker_image:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t chiragbaghra/python-project:weather-app-qa .
        docker push chiragbaghra/python-project:weather-app-qa
